name: Docker Image CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{ vars.var1}}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build and Run docker images
        run: |
          docker build -t images-test --no-cache .
          docker run --rm --name selenium2 images-test
